# fly.toml app configuration file generated for reactivities-haven2 on 2024-01-28T14:52:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-haven2'
primary_region = 'ams'

[build]
  image = 'dietbrand/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dv0h4pala"
  Cloudinary__ApiKey="679259388185949"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
